name: Run PowerShell Script

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string

jobs:
  run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        shell: pwsh
        run: |
          ./script.ps1 -Name "${{ inputs.name }}"
